### ISSUE TITLE
Zora Opstack genesis and rollup json

### ISSUE THREAD

**Issue by nodiesBlade** [ourzora/zora-docs#117]
Hi!

Our team currently operates https://nodies.org, and we support multiple RPC networks. Our goal is to ensure that L2's on OPStack are supported and we currently supported Optimism, Base, and Metis. We'd love to add Zora our fourth provider. Does zora have any documentation on building a node for their network? I cannot find the genesis or rollup.json for us to be able to support the network and provide RPC access to users.

**Comment by jgresham** [comment]
+1 I'm interested in this as-well

**Comment by iainnash** [comment]
See here: https://github.com/conduitxyz/node
