### ISSUE TITLE
docs: update link in zora-docs/docs/guides /connect-wallet-react.mdx

### ISSUE THREAD

**Issue by alexanderblv** [ourzora/zora-docs#153]
https://github.com/ourzora/zora-docs/blob/cd7b5e6104c41460491f208bd95b172e5b896054/docs/guides/connect-wallet-react.mdx?plain=1#L19

Line 19, the data is outdated. A big update has been released. Here is a new link:
https://docs.ethers.org/v6/api/providers/#Signer
In the new version, the information is more complete and clear

For some reason I can't create a Pull Request and because of this I have to create Issue

**Comment by iainnash** [comment]
Hello! We've deprecated these docs and replaced them with m
