### ISSUE TITLE
A couple of minor typos in the Nouns Builder docs

### ISSUE THREAD

**Issue by ibrosen** [ourzora/zora-docs#91]
I've been reading through the Nouns Builder docs - they're amazing. While reading I ran across a couple of super minor typos, thought I'd flag them for you!

https://github.com/ourzora/zora-docs/blob/main/docs/guides/builder-deployment.mdx
- "Obtain Geroli ETH" -> "Obtain Goerli ETH"

https://github.com/ourzora/zora-docs/blob/main/docs/smart-contracts/nouns-builder/auctions.mdx
- "hand over control of the auction house to the treasure" -> "hand over control of the auction house to the treasury"

**Comment by IsabellaSmallcombe** [comment]
hi @ibrosen! Thank you so much, i'll push up a PR to fix these
