### ISSUE TITLE
Trouble building docs @ Node v18.12.0

### ISSUE THREAD

**Issue by salieflewis** [ourzora/zora-docs#96]
I'm trying to pull down a fresh version of the docs, but having trouble getting them to build. I'm attaching a screenshot of the error but light googling is telling me this might having something to do with the version of Node that I'm running. I'm curious what version you guys are using locally.

@anader123 

<img width="620" alt="CleanShot 2023-02-07 at 11 03 32@2x" src="https://user-images.githubusercontent.com/37086973/217297631-93ea6d57-7d69-4028-bc51-b2abd928a115.png">

**Comment by anader123** [comment]
Interesting, I'm not having this error. I'm using Node v16.9.1
